/* Generated by gen_constants.rb -- do not edit */

#include "amalgalite3.h";
/**
 * Document-class: Amalgalite::SQLite3::Constants
 *
 * class holding constants in the sqlite extension
 */
void Init_amalgalite3_constants( )
{

    VALUE ma  = rb_define_module("Amalgalite");
    VALUE mas = rb_define_module_under(ma, "SQLite3");

    /*
     * module encapsulating all the SQLite C extension constants 
     */
    VALUE mC = rb_define_module_under( mas, "Constants");
    /**
     * module encapsulating the SQLite3 C extension constants for DBStatus 
     */
    VALUE mC_DBStatus = rb_define_module_under(mC, "DBStatus");

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_DBStatus, "LOOKASIDE_USED", INT2FIX(SQLITE_DBSTATUS_LOOKASIDE_USED));

    /**
     * module encapsulating the SQLite3 C extension constants for DataType 
     */
    VALUE mC_DataType = rb_define_module_under(mC, "DataType");

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_DataType, "BLOB", INT2FIX(SQLITE_BLOB));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_DataType, "FLOAT", INT2FIX(SQLITE_FLOAT));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_DataType, "INTEGER", INT2FIX(SQLITE_INTEGER));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_DataType, "NULL", INT2FIX(SQLITE_NULL));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_DataType, "TEXT", INT2FIX(SQLITE_TEXT));

    /**
     * module encapsulating the SQLite3 C extension constants for Open 
     */
    VALUE mC_Open = rb_define_module_under(mC, "Open");

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Open, "CREATE", INT2FIX(SQLITE_OPEN_CREATE));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Open, "READONLY", INT2FIX(SQLITE_OPEN_READONLY));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Open, "READWRITE", INT2FIX(SQLITE_OPEN_READWRITE));

    /**
     * module encapsulating the SQLite3 C extension constants for ResultCode 
     */
    VALUE mC_ResultCode = rb_define_module_under(mC, "ResultCode");

    /*  4 -- Callback routine requested an abort */
    rb_define_const(mC_ResultCode, "ABORT", INT2FIX(SQLITE_ABORT));

    /*  23 -- Authorization denied */
    rb_define_const(mC_ResultCode, "AUTH", INT2FIX(SQLITE_AUTH));

    /*  5 -- The database file is locked */
    rb_define_const(mC_ResultCode, "BUSY", INT2FIX(SQLITE_BUSY));

    /*  14 -- Unable to open the database file */
    rb_define_const(mC_ResultCode, "CANTOPEN", INT2FIX(SQLITE_CANTOPEN));

    /*  19 -- Abort due to constraint violation */
    rb_define_const(mC_ResultCode, "CONSTRAINT", INT2FIX(SQLITE_CONSTRAINT));

    /*  11 -- The database disk image is malformed */
    rb_define_const(mC_ResultCode, "CORRUPT", INT2FIX(SQLITE_CORRUPT));

    /*  101 -- sqlite3_step() has finished executing */
    rb_define_const(mC_ResultCode, "DONE", INT2FIX(SQLITE_DONE));

    /*  16 -- Database is empty */
    rb_define_const(mC_ResultCode, "EMPTY", INT2FIX(SQLITE_EMPTY));

    /*  1 -- SQL error or missing database */
    rb_define_const(mC_ResultCode, "ERROR", INT2FIX(SQLITE_ERROR));

    /*  24 -- Auxiliary database format error */
    rb_define_const(mC_ResultCode, "FORMAT", INT2FIX(SQLITE_FORMAT));

    /*  13 -- Insertion failed because database is full */
    rb_define_const(mC_ResultCode, "FULL", INT2FIX(SQLITE_FULL));

    /*  2 -- Internal logic error in SQLite */
    rb_define_const(mC_ResultCode, "INTERNAL", INT2FIX(SQLITE_INTERNAL));

    /*  9 -- Operation terminated by sqlite3_interrupt() */
    rb_define_const(mC_ResultCode, "INTERRUPT", INT2FIX(SQLITE_INTERRUPT));

    /*  10 -- Some kind of disk I/O error occurred */
    rb_define_const(mC_ResultCode, "IOERR", INT2FIX(SQLITE_IOERR));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_BLOCKED", INT2FIX(SQLITE_IOERR_BLOCKED));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_DELETE", INT2FIX(SQLITE_IOERR_DELETE));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_DIR_FSYNC", INT2FIX(SQLITE_IOERR_DIR_FSYNC));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_FSTAT", INT2FIX(SQLITE_IOERR_FSTAT));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_FSYNC", INT2FIX(SQLITE_IOERR_FSYNC));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_NOMEM", INT2FIX(SQLITE_IOERR_NOMEM));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_RDLOCK", INT2FIX(SQLITE_IOERR_RDLOCK));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_READ", INT2FIX(SQLITE_IOERR_READ));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_SHORT_READ", INT2FIX(SQLITE_IOERR_SHORT_READ));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_TRUNCATE", INT2FIX(SQLITE_IOERR_TRUNCATE));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_UNLOCK", INT2FIX(SQLITE_IOERR_UNLOCK));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "IOERR_WRITE", INT2FIX(SQLITE_IOERR_WRITE));

    /*  6 -- A table in the database is locked */
    rb_define_const(mC_ResultCode, "LOCKED", INT2FIX(SQLITE_LOCKED));

    /*  20 -- Data type mismatch */
    rb_define_const(mC_ResultCode, "MISMATCH", INT2FIX(SQLITE_MISMATCH));

    /*  21 -- Library used incorrectly */
    rb_define_const(mC_ResultCode, "MISUSE", INT2FIX(SQLITE_MISUSE));

    /*  22 -- Uses OS features not supported on host */
    rb_define_const(mC_ResultCode, "NOLFS", INT2FIX(SQLITE_NOLFS));

    /*  7 -- A malloc() failed */
    rb_define_const(mC_ResultCode, "NOMEM", INT2FIX(SQLITE_NOMEM));

    /*  26 -- File opened that is not a database file */
    rb_define_const(mC_ResultCode, "NOTADB", INT2FIX(SQLITE_NOTADB));

    /*  12 -- NOT USED. Table or record not found */
    rb_define_const(mC_ResultCode, "NOTFOUND", INT2FIX(SQLITE_NOTFOUND));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_ResultCode, "OK", INT2FIX(SQLITE_OK));

    /*  3 -- Access permission denied */
    rb_define_const(mC_ResultCode, "PERM", INT2FIX(SQLITE_PERM));

    /*  15 -- NOT USED. Database lock protocol error */
    rb_define_const(mC_ResultCode, "PROTOCOL", INT2FIX(SQLITE_PROTOCOL));

    /*  25 -- 2nd parameter to sqlite3_bind out of range */
    rb_define_const(mC_ResultCode, "RANGE", INT2FIX(SQLITE_RANGE));

    /*  8 -- Attempt to write a readonly database */
    rb_define_const(mC_ResultCode, "READONLY", INT2FIX(SQLITE_READONLY));

    /*  100 -- sqlite3_step() has another row ready */
    rb_define_const(mC_ResultCode, "ROW", INT2FIX(SQLITE_ROW));

    /*  17 -- The database schema changed */
    rb_define_const(mC_ResultCode, "SCHEMA", INT2FIX(SQLITE_SCHEMA));

    /*  18 -- String or BLOB exceeds size limit */
    rb_define_const(mC_ResultCode, "TOOBIG", INT2FIX(SQLITE_TOOBIG));

    /**
     * module encapsulating the SQLite3 C extension constants for Status 
     */
    VALUE mC_Status = rb_define_module_under(mC, "Status");

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "MALLOC_SIZE", INT2FIX(SQLITE_STATUS_MALLOC_SIZE));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "MEMORY_USED", INT2FIX(SQLITE_STATUS_MEMORY_USED));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "PAGECACHE_OVERFLOW", INT2FIX(SQLITE_STATUS_PAGECACHE_OVERFLOW));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "PAGECACHE_SIZE", INT2FIX(SQLITE_STATUS_PAGECACHE_SIZE));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "PAGECACHE_USED", INT2FIX(SQLITE_STATUS_PAGECACHE_USED));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "PARSER_STACK", INT2FIX(SQLITE_STATUS_PARSER_STACK));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "SCRATCH_OVERFLOW", INT2FIX(SQLITE_STATUS_SCRATCH_OVERFLOW));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "SCRATCH_SIZE", INT2FIX(SQLITE_STATUS_SCRATCH_SIZE));

    /* no meaningful autogenerated documentation -- constant is self explanatory ?*/
    rb_define_const(mC_Status, "SCRATCH_USED", INT2FIX(SQLITE_STATUS_SCRATCH_USED));

}
